/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_three_phoneinfotest_NativeMethod */

#ifndef _Included_com_three_phoneinfotest_NativeMethod
#define _Included_com_three_phoneinfotest_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_three_phoneinfotest_NativeMethod
 * Method:    readFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_three_phoneinfotest_NativeMethod_readFile
  (JNIEnv *,  jclass);

#ifdef __cplusplus
}
#endif
#endif
